[package]
name = "bytetrawl"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Cross-platform application and binary inspection workbench"

[dependencies]
anyhow.workspace = true
bytetrawl-core = { path = "../bytetrawl-core" }
bytetrawl-format = { path = "../bytetrawl-format" }
bytetrawl-analysis = { path = "../bytetrawl-analysis" }
bytetrawl-ios = { path = "../bytetrawl-ios" }
bytetrawl-compare = { path = "../bytetrawl-compare" }
bytetrawl-android = { path = "../bytetrawl-android" }
bytetrawl-windows = { path = "../bytetrawl-windows" }
bytetrawl-linux = { path = "../bytetrawl-linux" }
bytetrawl-tools = { path = "../bytetrawl-tools" }
gpui.workspace = true
gpui-component.workspace = true
rfd.workspace = true
uuid.workspace = true
indexmap.workspace = true
serde_json.workspace = true

[[bin]]
name = "ByteTrawl"
path = "src/main.rs"
test = false
