[package]
name = "bytetrawl-policy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytetrawl-core = { path = "../bytetrawl-core" }
bytetrawl-ios = { path = "../bytetrawl-ios" }
bytetrawl-compare = { path = "../bytetrawl-compare" }
bytetrawl-android = { path = "../bytetrawl-android" }
bytetrawl-windows = { path = "../bytetrawl-windows" }
bytetrawl-linux = { path = "../bytetrawl-linux" }
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
